### ISSUE TITLE
garmin URL not working in some browsers?

### ISSUE THREAD

**Issue by ccwyoung** [dproctor/headed-south#14]
From Phil: 

"We were out somewhere, and when I clicked on the link you sent me (on my iPhone) it worked fine. But, at home, on my PC (using Chrome), when I click on the same link, I get the error message again:

"Whoops! The MapShare URL does not exist."

When I switch to Edge, I don't get that error message, but entering the password just brings me back to the password page again, now with a blank password. No error message at all.

Finally, got it to work with Mozilla Firefox."

-- could very well be the user and not the UI, but thought I'd submit it as an issue just in case. :)

**Comment by dproctor** [comment]
I've noticed this a few times as well. As far as I can tell, the Garmin
website is just broken, as it will sometimes load after refreshing the page
(same browser, same everything).

I'll keep this issue open until I have a chance to look into a bit more,
but I'm not optimistic that it's fixable on my end.

**Comment by dproctor** [comment]
Yeah, unfortunately there isn't anything I can do about this. Seems that Garmin mapshare is just kind of janky. I'll just add a notice to the website about the issue. Thanks!
